<?php
/**
 * Created by PhpStorm.
 * User: Mike
 * Date: 2/19/2014
 * Time: 7:01 PM
 */

use Illuminate\Database\Seeder;
use App\Standard;

class StandardsSeeder extends Seeder{
    public function run(){
        DB::table('standards')->delete();

        $standards =[
            /**AU/CAT*/
            ["Interpersonal Attributes",1,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Design Process",1,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Industry Experience",1,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Career Awareness",1,"http://www.nextgenscience.org/next-generation-science-standards"],


            /**NGSS*/
            ["Patterns",3, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["Cause & Effect: Mechanism & Explanation",3, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["Scale, Proportion, & Quantity ",3, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["Systems & System Models",3, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["Energy & Matter: Flow, Cycle, Conservation",3, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["Structure & Function",3, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["Stability & Change",3, "http://www.nextgenscience.org/next-generation-science-standards"],

            ["PS1A - Structure & Properties of Matter ",4, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["PS1B - Chemical Reactions ",4, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["PS1C - Nuclear Processes",4, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["PS2A - Forces & Motion ",4, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["PS2B - Types of Interactions",4, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["PS2C - Stability & Instability ",4, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["PS3A - Definitions of Energy",4, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["PS3B - Energy: Conservation & Transfer",4, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["PS3C - Energy & Forces",4, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["PS3D - Energy in Chemical Processes & Life ",4, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["PS4A - Wave Properties ",4, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["PS4B - Electromagnetic Radiation",4, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["PS4C - Information Technologies",4, "http://www.nextgenscience.org/next-generation-science-standards"],

            ["LS1A - Structure & Function",5, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["LS1B - Growth & Development",5, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["LS1C - Organization in Organisms",5, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["LS1D - Information Processing",5, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["LS2A - Relationships in Ecosystems",5, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["LS2B - Cycles in Ecosystems",5, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["LS2C - Ecosystem Dynamics",5, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["LS2D - Social Interactions & Behavior",5, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["LS3A - Inheritance of Traits",5, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["LS3B - Variation of Traits",5, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["LS4A - Evidence of Common Ancestry",5, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["LS4B - Natural Selection",5, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["LS4C - Adaptation",5, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["LS4D - Biodiversity & Humans",5, "http://www.nextgenscience.org/next-generation-science-standards"],

            ["ESS1A - The Universe & Its Stars",6, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["ESS1B - Earth & the Solar System",6, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["ESS1C - History of the Planet Earth",6, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["ESS2A - Earth Materials & Systems ",6, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["ESS2B - Plate Tectonics/Large Scale Systems",6, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["ESS2C - Role of Water on Earth",6, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["ESS2D - Weather & Climate",6, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["ESS2E - Biogeology",6, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["ESS3A - Natural Resources ",6, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["ESS3B - Natural Hazards",6, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["ESS3C - Human Impacts on Earth Systems",6, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["ESS3D - Global Climate Change",6, "http://www.nextgenscience.org/next-generation-science-standards"],

            ["ETS1A - Defining & Delimiting an Engineering Problem",7, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["ETS1B - Developing Possible Solutions",7, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["ETS1C - Optimizing the Design Solution",7, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["ETS2A - Interdependence of Science, Engineering & Technology",7, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["ETS2B - Influence of Science, Engineering & Technology on Society & the Natural World",7, "http://www.nextgenscience.org/next-generation-science-standards"],

            ["Asking Questions & Defining Problems",8, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["Developing & Using Models ",8, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["Planning & Carrying Out Investigations",8, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["Analyzing & Interpreting Data",8, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["Mathematics & Computational Thinking",8, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["Construct Explanations & Design Solutions",8, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["Engaging in Argument from Evidence ",8, "http://www.nextgenscience.org/next-generation-science-standards"],
            ["Obtain, Evaluate, Communicate Information",8, "http://www.nextgenscience.org/next-generation-science-standards"],



            /**Math*/
            ["CC.3.MD.7d",10,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.MD.8",10,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.G.1",10,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.G.2",10,"http://www.nextgenscience.org/next-generation-science-standards"],

            ["CC.4.OA.1",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.OA.2",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.OA.3",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.OA.4",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.OA.5",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.NBT.1",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.NBT.2",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.NBT.3",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.NBT.4",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.NBT.5",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.NBT.6",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.NF.1",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.NF.2",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.NF.3",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.NF.3a",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.NF.3b",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.NF.3c",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.NF.4",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.NF.4a",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.NF.4b",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.NF.4c",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.NF.5",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.NF.6",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.NF.7",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.MD.1",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.MD.2",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.MD.3",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.MD.4",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.MD.5",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.MD.6",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.MD.7",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.G.1",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.G.2",11,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.G.3",11,"http://www.nextgenscience.org/next-generation-science-standards"],


            ["CC.5.OA.1",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.OA.2",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.OA.3",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.NBT.1",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.NBT.2",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.NBT.3",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.NBT.3a",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.NBT.3b",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.NBT.4",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.NBT.5",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.NBT.6",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.NBT.7",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.NF.1",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.NF.2",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.NF.3",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.NF.4",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.NF.4a",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.NF.4b",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.NF.5",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.NF.6",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.NF.7",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.NF.7a",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.NF.7b",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.NF.7c",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.MD.1",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.MD.2",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.MD.3",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.MD.4",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.MD.5",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.MD.5a",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.MD.5b",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.MD.5c",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.G.1",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.G.2",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.G.3",12,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.G.4",12,"http://www.nextgenscience.org/next-generation-science-standards"],


            ["CC.6.RP.1",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.RP.2",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.RP.3",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.RP.3a",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.RP.3b",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.RP.3c",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.RP.3d",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.NS.1",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.NS.2",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.NS.3",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.NS.4",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.NS.5",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.NS.6",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.NS.6a",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.NS.6b",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.NS.6c",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.NS.7",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.NS.7a",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.NS.7b",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.NS.7c",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.NS.7d",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.NS.8",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.EE.1",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.EE.2",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.EE.2a",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.EE.2b",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.EE.2c",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.EE.3",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.EE.4",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.EE.5",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.EE.6",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.EE.7",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.EE.8",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.EE.9",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.G.1",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.G.2",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.G.3",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.G.4",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.SP.1",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.SP.2",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.SP.3",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.SP.4",13,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.SP.5",13,"http://www.nextgenscience.org/next-generation-science-standards"],



            ["CC.7.RP.1",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.RP.2",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.RP.2a",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.RP.2b",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.RP.2c",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.RP.2d",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.RP.3",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.NS.1",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.NS.1a",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.NS.1b",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.NS.1c",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.NS.1d",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.NS.2",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.NS.2a",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.NS.2b",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.NS.2c",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.NS.2d",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.NS.3",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.EE.1",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.EE.2",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.EE.3",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.EE.4",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.EE.4a",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.EE.4b",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.G.1",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.G.2",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.G.3",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.G.4",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.G.5",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.G.6",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SP.1",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SP.2",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SP.3",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SP.4",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SP.5",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SP.6",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SP.7",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SP.7a",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SP.7b",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SP.8",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SP.8a",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SP.8b",14,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SP.8c",14,"http://www.nextgenscience.org/next-generation-science-standards"],


            ["CC.8.NS.1",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.NS.2",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.EE.1",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.EE.2",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.EE.3",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.EE.4",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.EE.5",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.EE.6",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.EE.7",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.EE.7a",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.EE.7b",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.EE.8",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.EE.8a",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.EE.8b",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.EE.8c",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.F.1",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.F.2",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.F.3",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.F.4",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.F.5",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.G.1",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.G.2",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.G.3",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.G.4",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.G.5",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.G.6",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.G.7",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.G.8",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.G.9",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.SP.1",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.SP.2",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.SP.3",15,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.SP.4",15,"http://www.nextgenscience.org/next-generation-science-standards"],

            /**ELA*/
            ["CC.3.R.L.1",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.L.2",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.L.3",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.L.4",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.L.5",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.L.6",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.L.7",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.L.9",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.L.10",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.I.1",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.I.2",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.I.3",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.I.4",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.I.5",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.I.6",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.I.7",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.I.8",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.I.9",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.I.10",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.F.3",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.F.3.a",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.F.3.b",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["c CC.3.R.F.3.c",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.F.3.d",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.F.4",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.F.4.a",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.F.4.b",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.R.F.4.c",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.W.1",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.W.1.a",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.W.1.b",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.W.1.c",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.W.1.d",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.W.2",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.W.2.a",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.W.2.b",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.W.2.d",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.W.3",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.W.3.a",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.W.3.b",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.W.3.c",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.W.3.d",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.W.4",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.W.5",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.W.6",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.W.7",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.W.8",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.W.10",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.SL.1 ",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.SL.1.a",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.SL.1.b",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.SL.1.c",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.SL.1.d",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.SL.2",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.SL.3",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.SL.4",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.SL.5",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.SL.6",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.1",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.1.a",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.1.b",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.1.c",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.1.d",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.1.e",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.1.f",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.1.g",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.1.h",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.1.i",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.2",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.2.a",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.2.b",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.2.c",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.2.d",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.2.e",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.2.f",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.2.g",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.3",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.3.a",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.3.b",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.4",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.4.a",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.4.b",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.4.c",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.4.d",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.5",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.5.a",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.5.b",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.5.c",17,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.3.L.6",17,"http://www.nextgenscience.org/next-generation-science-standards"],



            ["CC.4.R.L.1",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.L.2",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.L.3",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.L.4",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.L.5",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.L.6",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.L.7",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.L.9",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.L.10",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.I.1",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.I.2",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.I.3",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.I.4",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.I.5",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.I.6",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.I.7",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.I.8",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.I.9",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.I.10",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.F.3",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.F.3.a",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.F.4",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.F.4.a",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.F.4.b",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.R.F.4.c",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.1",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.1.a",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.1.b",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.1.c",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.1.d",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.2",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.2.a",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.2.b",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.2.c",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.2.d",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.2.e",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.3",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.3.a",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.3.b",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.3.c",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.3.d",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.3.e",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.4",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.5",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.6",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.7",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.8",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.9",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.9.a",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.9.b",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.W.10",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.SL.1",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.SL.1.a",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.SL.1.b",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.SL.1.c",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.SL.1.d",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.SL.2",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.SL.3",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.SL.4",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.SL.5",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.SL.6",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.1",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.1.a",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.1.b",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.1.c",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.1.d",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.1.e",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.1.f",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.1.g",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.2",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.2.a",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.2.b",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.2.c",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.2.d",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.3",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.3.a",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.3.b",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.3.c",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.4",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.4.a",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.4.b",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.4.c",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.5",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.5.a",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.5.b",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.5.c",18,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.4.L.6",18,"http://www.nextgenscience.org/next-generation-science-standards"],


            ["CC.5.R.L.1",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.R.L.2",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.R.L.3",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.R.L.4",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.R.L.5",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.R.L.6",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.R.L.7",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.R.L.9",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.R.L.10",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.R.I.1",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.R.I.2",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.R.I.3",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.R.I.4",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.R.I.5",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.R.I.6",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.R.I.7",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.R.I.8",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.R.I.9",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.R.I.10",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.R.F.3",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.R.F.3.a",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.R.F.4",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.1.a",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.1.b",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.1.c",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.1.d",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.2",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.2.a",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.2.b",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.2.c",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.2.d",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.2.e",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.3",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.3.a",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.3.b",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.3.c",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.3.d",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.3.e",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.4",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.5",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.6",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.7",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.8",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.9",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.9.a",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.9.b",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.W.10",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.SL.1",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.SL.1.a",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.SL.1.b",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.SL.1.c",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.SL.1.d",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.SL.2",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.SL.3",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.SL.4",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.SL.5",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.SL.6",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.1",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.1.a",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.1.b",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.1.c",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.1.d",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.1.e",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.2",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.2.a",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.2.b",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.2.c",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.2.d",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.2.e",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.3",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.3.a",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.3.b",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.4",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.4.a",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.4.b",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.4.c",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.5",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.5.a",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.5.b",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.5.c",19,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.5.L.6",19,"http://www.nextgenscience.org/next-generation-science-standards"],


            ["CC.6.R.L.1",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.R.L.2",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.R.L.3",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.R.L.4",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.R.L.5",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.R.L.6",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.R.L.7",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.R.L.9",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.R.L.10",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.R.I.1",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.R.I.2",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.R.I.3",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.R.I.4",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.R.I.5",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.R.I.6",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.R.I.7",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.R.I.9",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.R.I.10",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.1",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.1.a",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.1.b",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.1.c",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.1.d",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.1.e",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.2",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.2.a",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.2.b",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.2.c",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.2.e",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.2.f",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.3",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.3.a",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.3.b",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.3.c",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.3.d",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.3.e",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.4",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.5",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.6",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.7",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.8",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.9",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.9.a",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.9.b",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.W.10",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.SL.1 ",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.SL.1.a",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.SL.1.b",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.SL.1.c",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.SL.1.d",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.SL.2",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.SL.3",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.SL.4",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.SL.5",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.SL.6",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.L.1",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.L.1.a",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.L.1.b",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.L.1.c",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.L.1.d",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.L.1.e",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.L.2",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.L.2.a",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.L.2.b",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.L.3",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.L.3.a",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.L.3.b",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.L.4",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.L.4.a",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.L.4.b",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.L.4.c",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.L.4.d",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.L.5",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.L.5.a",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.L.5.b",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.L.5.c",20,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6.L.6",20,"http://www.nextgenscience.org/next-generation-science-standards"],

            ["CC.7.R.L.1",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.R.L.2",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.R.L.3",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.R.L.4",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.R.L.5",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.R.L.6",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.R.L.7",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.R.L.9",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.R.L.10",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.R.I.1",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.R.I.2",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.R.I.3",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.R.I.4",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.R.I.5",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.R.I.6",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.R.I.7",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.R.I.8",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.R.I.9",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.R.I.10",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            [" CC.7.W.1",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.1.a",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.1.b",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.1.c",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.1.d",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.1.e",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.2",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.2.a",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.2.b",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.2.c",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.2.d",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.2.e",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.2.f",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.3",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.3.a",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.3.b",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.3.c",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.3.d",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.3.e",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.4",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.5",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.6",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.7",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.8",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.9",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.9.a",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.9.b",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.W.10",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SL.1",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SL.1.a",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SL.1.b",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SL.1.c",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SL.1.d",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SL.2",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SL.3",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SL.4",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SL.5",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.SL.6",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.L.1",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.L.1.a",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.L.1.b",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.L.1.c",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.L.2",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.L.2.a",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.L.2.b",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.L.3",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.L.3.a",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.L.4",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.L.4.a",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.L.4.b",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.L.4.c",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.L.4.d",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.L.5",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.L.5.a",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.L.5.b",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.L.5.c",21,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.7.L.6",21,"http://www.nextgenscience.org/next-generation-science-standards"],


            ["CC.8.R.L.1",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.R.L.2",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.R.L.3",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.R.L.4",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.R.L.5",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.R.L.6",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.R.L.7",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.R.L.9",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.R.L.10",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.R.I.1",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.R.I.2",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.R.I.3",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.R.I.4",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.R.I.5",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.R.I.6",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.R.I.7",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.R.I.8",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.R.I.9",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.R.I.10",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.1",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.1.a",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.1.b",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.1.c",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.1.d",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.1.e",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.2",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.2.a",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.2.b",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.2.c",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.2.d",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.2.e",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.2.f",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.3",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.3.a",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.3.b",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.3.c",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.3.d",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.3.e",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.4",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.5",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.6 ",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.7",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.8",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.9",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.9.a",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.9.b",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.W.10",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.SL.1",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.SL.1.a",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.SL.1.b",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.SL.1.c",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.SL.1.d",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.SL.2",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.SL.3",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.SL.4",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.SL.5",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.SL.6",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.L.1",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.L.1.a",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.L.1.b",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.L.1.c",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.L.1.d",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.L.2",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.L.2.a",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.L.2.b",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.L.2.c",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.L.3",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.L.3.a",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.L.4",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.L.4.a",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.L.4.b",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.L.4.c",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.L.4.d",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.L.5",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.L.5.a",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.L.5.b",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.L.5.c",22,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.8.L.6",22,"http://www.nextgenscience.org/next-generation-science-standards"],

            ["CC.6-8.R.H.2",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.R.H.3",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.R.H.4",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.R.H.5",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.R.H.6",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.R.H.7",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.R.H.8",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.R.H.9",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.R.H.10",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.R.ST.1",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.R.ST.2",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.R.ST.3",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.R.ST.4",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.R.ST.5",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.R.ST.6",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.R.ST.7",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.R.ST.8",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.R.ST.9",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.R.ST.10",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.R.H.1",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.W.HST.1",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.W.HST.1.a",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.W.HST.1.b",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.W.HST.1.c",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.W.HST.1.d",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.W.HST.1.e",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.W.HST.2",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.W.HST.2.a",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.W.HST.2.b",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.W.HST.2.c",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.W.HST.2.d",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.W.HST.2.e",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.W.HST.2.f",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.W.HST.4",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.W.HST.5",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.W.HST.6",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.W.HST.7",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.W.HST.8",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.W.HST.9",23,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["CC.6-8.W.HST.10",23,"http://www.nextgenscience.org/next-generation-science-standards"],


            ["Agriculture Resources",24,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Architecture & Construction",24,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Energy",24,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Finance",24,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Health Science",24,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Information Technology",24,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Manufacturing",24,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Research & Development",24,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Transportation Distribution & Logistics",24,"http://www.nextgenscience.org/next-generation-science-standards"],


            ["Market/Cost Analysis",25,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Product Development & Engineering",25,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Raw Material",25,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Manufacturing Production",25,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Transportation/Logistics",25,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Utilization/Reuse",25,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Disposal/Recycling",25,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Sales/Projections",25,"http://www.nextgenscience.org/next-generation-science-standards"],


            ["Biomedical & Life Science",26,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Materials Science",26,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Field Studies",26,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["GEARS",26,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Energy",26,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Manufacturing, Modeling, & Design",26,"http://www.nextgenscience.org/next-generation-science-standards"],



            ["Agricultural Application",27,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Morton Arboretum",27,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Robert Crown",27,"http://www.nextgenscience.org/next-generation-science-standards"],
            ["Cabot Micro Electronics & Caterpillar Inc.",27,"http://www.nextgenscience.org/next-generation-science-standards"],




        ];

        foreach($standards as $standard){
            Standard::create(['name' => $standard[0],'category_id' => $standard[1], 'link' => $standard[2]]);
        }
    }
}